### ISSUE TITLE
JSONDecodeError when verifying with my own bitcoin-core full node

### ISSUE THREAD

**Issue by ivohuisjes** [opentimestamps/opentimestamps-client#104]
**Problem**
When I want to verify my timestamp .ots (submitted on february 27 with a opentimestamp client), using my own full bitcoin core node, I get the error:
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`ots --bitcoin-node http://myusername:mypassword@127.0.0.1:8332/ verify TEST.md.ots`

**Information about my system**
Linux (Arch based) x64
Python 3.7
opentimestamps-client v0.6.0 (installed with pip3)
python-bitcoinlib v0.9.0 (compiled from [source](https://github.com/petertodd/python-bitcoinlib))
Bitcoin core full node v0.17.1 in prune mode

**I have taken the following steps already**

- I tested if my full node's RPC is working using curl:

`curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getblockchaininfo", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/`
Response:
`{"result":{"chain":"main","blocks":565384,"headers":565384,"bestblockhash":"00000000000000000022c1b481300019343880e09283ab5d2275db28971c6ef4","difficulty":6071846049920.752,"mediantime":1551555181,"verificationprogress":0.9999977382872327,"initialblockdownload":false,"chainwork":"00000000000000000000000000000000000000000549044dfd4dcb35e944b6f0","size_on_disk":559128542,"pruned":true,"pruneheight":564946,"automatic_pruning":true,"prune_target_size":576716800,"softforks":[{"id":"bip34","version":2,"reject":{"status":true}},{"id":"bip66","version":3,"reject":{"status":true}},{"id":"bip65","version":4,"reject":{"status":true}}],"bip9_softforks":{"csv":{"status":"active","startTime":1462060800,"timeout":1493596800,"since":419328},"segwit":{"status":"active","startTime":1479168000,"timeout":1510704000,"since":481824}},"warnings":""},"error":null,"id":"curltest"}`

- Read the Known problems. It states the problem, I am having, is a python package named bitcoin. I followed the instructions to reinstall python-bitcoinlib) It gave me a warning the most recent version of python-bitcoinlib (0.10.1) was too high <0.10.0 >=0.9.0. So I manually installed v0.9.0 through pip3

- Since the above solution did not work, I removed the packages bitcoin and python-bitcoinlib again and manually compiled and installed Peter Todd's python-bitcoinlib, checked out v0.9.0

I still get the following error:
`Assuming target filename is 'TEST.md'
Got 1 attestation(s) from cache
Traceback (most recent call last):
  File "/usr/bin/ots", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/otsclient/ots.py", line 34, in main
    args.cmd_func(args)
  File "/usr/lib/python3.7/site-packages/otsclient/cmds.py", line 490, in verify_command
    if not verify_timestamp(detached_timestamp.timestamp, args):
  File "/usr/lib/python3.7/site-packages/otsclient/cmds.py", line 412, in verify_timestamp
    block_count = proxy.getblockcount()
  File "/usr/lib/python3.7/site-packages/python_bitcoinlib-0.9.0-py3.7.egg/bitcoin/rpc.py", line 450, in getblockcount
    return self._call('getblockcount')
  File "/usr/lib/python3.7/site-packages/python_bitcoinlib-0.9.0-py3.7.egg/bitcoin/rpc.py", line 219, in _call
    response = self._get_response()
  File "/usr/lib/python3.7/site-packages/python_bitcoinlib-0.9.0-py3.7.egg/bitcoin/rpc.py", line 250, in _get_response
    parse_float=decimal.Decimal)
  File "/usr/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`
Without passing my full node, I get the following:
`ots verify TEST.md.ots
Assuming target filename is 'TEST.md'
Got 1 attestation(s) from cache
Success! Bitcoin block 564857 attests existence as of 2019-02-27 CET`

**Comment by petertodd** [comment]
The fact that you can succesfully verify your timestamp without passing your full node as a command line option suggests that `ots` *is* able to talk to your full node.

See, Bitcoin Core has an "auto-setup" feature, that basically allows python-bitcoinlib to figure out automatically how to connect to your full node in your current setup. `ots` won't say "Success!" unless it's able to connect to your full node, so that auto-setup must be working correctly.

I'm guessing that on your setup `http://myusername:mypassword@127.0.0.1:8332/` simply isn't the correct way to connect to your node. E.g. maybe a password/username is incorrect or something. python-bitcoinlib's RPC error handling isn't great, so likely it's just failing due to that.

Unless you need to do something fancy, there's actually no need to use the `--bitcoin-node` option, so feel free to use `ots` without it.

**Comment by ivohuisjes** [comment]
Thanks for your reply. I can confirm I do not need to pass my full node with --bitcoin-node in order to verify, using my full node.
