### ISSUE TITLE
Failed to create timestamp: need at least 1 attestation but received 0 within timeout

### ISSUE THREAD

**Issue by lorenzodisidoro** [opentimestamps/opentimestamps-client#106]
I'm running a docker container of opentimestamps server, when I try to timestamp using javascript client it works:
```sh
➜  ~ ots-cli.js stamp -c http://127.0.0.1:14788 -m 1 test.txt
Submitting to remote calendar http://127.0.0.1:14788
The timestamp proof 'test.txt.ots' has been created!
```

but when I try using python client here is my output:
```sh
➜  ~ ots stamp -c http://127.0.0.1:14788 -m 1 test.txt
Submitting to remote calendar http://127.0.0.1:14788
Failed to create timestamp: need at least 1 attestation but received 0 within timeout
```

What's going wrong?

I'm currently working with this python version
```sh
➜  ~ python3 -V
Python 3.7.1
➜  ~ pip3 -V
pip 19.1.1 from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7)
```

**Update:**
The python client works if it's installed in the server container, so I presume that the problem is not the client.

**Comment by JMariadlcs** [comment]
Did you get a solution for that?

**Comment by k-allika** [comment]
Same issue here too while using Python command.

The first time I tried, I got 
`Failed to create timestamp: need at least 2 attestations but received 0 within timeout`

I ran the same command again with the same file name. Then I got:
`Failed to create timestamp: need at least 2 attestations but received 1 within timeout`

The third time, it was successful.

I am guessing that it's only able to receive 0 or 1 attestations in the timeout period. In my case, it seems to have received 1 attestation at a time in 2 times out of 3. Either the timeout period has to be increased or something has to be changed in the Python code.

**Comment by petertodd** [comment]
You can increase the timeout from the default 5 seconds with the `--timeout` option.

I suspect the issues you guys are having are due to poor internet connectivity or something similar. This doesn't seem to be a common issue. If I may ask, where are you located? I'm in Canada, relatively close to the physical location of the OTS calendars, so I might not have a typical experience.
