### ISSUE TITLE
$ots opens 'open text summarizer' in ubuntu, how can i access opentimestamps?

### ISSUE THREAD

**Issue by bjornym** [opentimestamps/opentimestamps-client#110]
hi,
not an issue i suppose, though i can't find any solution to this, being new to linux.
i've installed opentimestamps-client with pip3, seems ok.
but 'ots' refers to open text summarizer on my system, is there ways of changing or ways around this?

sorry for newbie question,
bj

**Comment by bjornym** [comment]
had to reboot, works now

**Comment by petertodd** [comment]
Great!

Sorry I didn't reply sooner; chances are the wrong `ots` was still in your shell's cache. That's probably why the reboot fixed it.

Let us know if you have any other issues. :)
