### ISSUE TITLE
on Archlinux does not complile opentimestamps-client-git package

### ISSUE THREAD

**Issue by gwpl** [opentimestamps/opentimestamps-client#113]
opentimestamps-client-git package - https://aur.archlinux.org/packages/opentimestamps-client-git/  - does not compile , full log: https://pastebin.com/4WCX4YXi , also as I mentioned in https://aur.archlinux.org/packages/opentimestamps-client-git/#comment-744828

**Comment by RCasatta** [comment]
maybe @drizzt could help?

**Comment by nobodyinperson** [comment]
This issue is not relevant anymore and can be closed.
