### ISSUE TITLE
Experimental litecoin validation

### ISSUE THREAD

**Issue by NCGThompson** [opentimestamps/opentimestamps-client#119]
In order to make a litecoin calendar serve, it would be very useful if I could use the client to test it. We could probably use a separator branch that verifies litecoin via a calendar server rather than a local node.

**Comment by NCGThompson** [comment]
I want to add that litecoin transactions are a lot cheaper than bitcoin right now. Litecoin calendar servers will be able to anchor much more frequently for the same price.

**Comment by petertodd** [comment]
AFAIK no-one uses the litecoin functionality, so closing.
