### ISSUE TITLE
Unable to verify via CLI

### ISSUE THREAD

**Issue by tigger04** [opentimestamps/opentimestamps-client#134]
Hi - first off, I just discovered this project and I am a big fan of the idea and impressed with it's implementation. Thank you for this wonderful OSS project :)

To the point .. I understood from the README that upon installing opentimestamps-client and its dependencies I should be good to go and run `ots stamp` and `ots verify` - please set me straight if i am missing something. I am unsure if I am finding a bug or simply that I have misunderstood what I need to do to set up and (do I need to additionally) configure the client.

Here's the problem - for, say, `hello-world.txt` in `/examples` ..

```
~/code/python/opentimestamps-client/examples
$ ots verify hello-world.txt.ots
Assuming target filename is 'hello-world.txt'
Could not connect to Bitcoin node: Cookie file unusable ([Errno 2] No such file or directory: '/Users/tigger/Library/Application Support/Bitcoin/.cookie') and rpcpassword not specified in the configuration file: '/Users/tigger/Library/Application Support/Bitcoin/bitcoin.conf'
🔴 ~/code/python/opentimestamps-client/examples
$
```

Yet `ots stamp` looks good ..

```
~/nc/desk/proofs
$ ots stamp foo.bar
Submitting to remote calendar https://a.pool.opentimestamps.org
Submitting to remote calendar https://b.pool.opentimestamps.org
Submitting to remote calendar https://a.pool.eternitywall.com
Submitting to remote calendar https://ots.btc.catallaxy.com
~/nc/desk/proofs
$ 
```

Preliminarily, verify looks to be doing what's expected ..

```
~/nc/desk/proofs
$ ots verify foo.bar.ots
Assuming target filename is 'foo.bar'
Calendar https://btc.calendar.catallaxy.com: Pending confirmation in Bitcoin blockchain
Calendar https://alice.btc.calendar.opentimestamps.org: Pending confirmation in Bitcoin blockchain
Calendar https://finney.calendar.eternitywall.com: Pending confirmation in Bitcoin blockchain
Calendar https://bob.btc.calendar.opentimestamps.org: Pending confirmation in Bitcoin blockchain
🔴 ~/nc/desk/proofs
$ 
```

But when I come back a few hours later:

```
~/nc/desk/proofs
$ ots verify foo.bar.ots
Assuming target filename is 'foo.bar'
Got 1 attestation(s) from https://bob.btc.calendar.opentimestamps.org
Got 1 attestation(s) from https://btc.calendar.catallaxy.com
Got 1 attestation(s) from https://finney.calendar.eternitywall.com
Got 1 attestation(s) from https://alice.btc.calendar.opentimestamps.org
Could not connect to Bitcoin node: Cookie file unusable ([Errno 2] No such file or directory: '/Users/tigger/Library/Application Support/Bitcoin/.cookie') and rpcpassword not specified in the configuration file: '/Users/tigger/Library/Application Support/Bitcoin/bitcoin.conf'
🔴 ~/nc/desk/proofs
$ 
```

Initially I just assumed this was a Mac/BSD peculiarity or perhaps just Apple ARM M1 weirdness which more often than not is the case and I just need to dig a little deeper to find a workaround or solution.

But then on my much less pretentious Dell laptop, intel x86_64 chip running Linux (Arch, btw), same behaviour ..

```
~/code/python/opentimestamps-client/examples
$ ots verify hello-world.txt.ots
Assuming target filename is 'hello-world.txt'
Could not connect to Bitcoin node: Cookie file unusable ([Errno 2] No such file or directory: '/home/chris/.bitcoin/.cookie') and rpcpassword not specified in the configuration file: '/home/chris/.bitcoin/bitcoin.conf'
🔴 ~/code/python/opentimestamps-client/examples
$ 
```

And the same behaviour described above when stamping/verifying my own files.

Digging around the issues log,  I get the impression I may need to download the bitcoin blockchain in order to `ots verify` from the CLI - is this the case?

If so, then I can probably just rely on the 4 calendar server attestations, right?

In that case, please help me understand how to read the output of ots verify that I'm seeing
- in relation to examples/hello-world.txt.ots - why are there no calendar attestatoins for any of the examples, only an error
- how confident can I be in the output of `ots verify` on my own files which appear to affirm the timestamp in 4 calendar servers but then shows an error. Does this mean, stamp looks good, just can't verify directly as you don't have the bitcoin blockchain configured locally, or am I seeing some problem with my timestamp, or a bug?

Thanks in advance for your time - any help/info greatly appreciated.

**Comment by RCasatta** [comment]
> stamp looks good, just can't verify directly as you don't have the bitcoin blockchain configured locally

This is correct.

> If so, then I can probably just rely on the 4 calendar server attestations, right?

The point of OpenTimestamps is that once you upgrade your proof you haven't to trust any third party, you can check your ots proof against your bitcoin node.

The node can be pruned (you don't need to store the entire blockchain).

You can find more information: https://petertodd.org/2016/opentimestamps-announcement
https://opentimestamps.org

**Comment by petertodd** [comment]
Note that you can use the `--no-bitcoin` option in conjunction with a block explorer you trust to manually verify Bitcoin attestations. For example:

```
user@dev-ots:~/opentimestamps-client/examples$ ots --no-bitcoin verify hello-world.txt.ots 
Assuming target filename is 'hello-world.txt'
Not checking Bitcoin attestation; Bitcoin disabled
To verify manually, check that Bitcoin block 358391 has merkleroot 8a1b66ecb7cbd07d8139a7e7d7f2c41aab1f5009b8364aaf61d03ad245e47e00
```

If you to go, eg, https://mempool.space, find that block, and click the "details" tab you can see that the merkleroot in question does in fact match.
