### ISSUE TITLE
Bad gateway [alice.btc.calendar.opentimestamps.org]

### ISSUE THREAD

**Issue by twofaktor** [opentimestamps/opentimestamps-client#135]
Hi, I was checking an ots verification when I saw this:

![imagen](https://user-images.githubusercontent.com/89636253/234319731-97ca82e1-29ea-4385-836a-05efc005a5fd.png)

![imagen](https://user-images.githubusercontent.com/89636253/234319984-9afa2b6b-e82b-4b1a-a42e-3e469814182c.png)

**Comment by petertodd** [comment]
That just means that the Alice calendar was down. It's up again.

You only need one calendar to validate a timestamp.
