### ISSUE TITLE
Checking for completeness / doublespend protection

### ISSUE THREAD

**Issue by RyanSinger** [opentimestamps/opentimestamps-client#30]
Hi Peter,

I'm interested in using OpenTimestamps for signed git transactions, but I have an additional requirement: The user checking the timestamp needs to know that they have the most recent commit, and that there isn't a competing git tree also signed by the same developer.

This is a feature request.

Ryan

**Comment by petertodd** [comment]
Well, I think that's very much out of scope for OpenTimestamps itself - that's a proof-of-uniqueness rather than a timestamp - but it is something I'm definitely interested in working on! I've got some potential designs that can be used.

I'd suggest you contact me via email to discuss further.
