### ISSUE TITLE
Installation in Debian Stretch

### ISSUE THREAD

**Issue by juestr** [opentimestamps/opentimestamps-client#52]
I had some problems installing in a Debian Stretch distribution where I never did any python3 development before. I had to search around a bit to solve this with:

    sudo apt-get install python3-dev python3-setuptools python3-wheel 

You might want to add this to the README or somewhere else, as I don't think it's obvious to everyone. Also I hope longer term you do plan to make this a proper pip3-installable package?

Apart from this, great work, I am going to timestamp my archive now...

**Comment by petertodd** [comment]
Good idea!

Is python3-setuptools actually sufficient? Or do you also need python3-pip?

We might want to also add the build-essential package to that list, as it's generally needed for building stuff on Debian. It'd be good if someone tests this on an absolutely bare-minimum Debian install.

**Comment by juestr** [comment]
I already had pip3 installed for some reason, you have to add it to the list. build-essentials is not strictly needed due to dependencies.

I tested the following in a new strech debootstrap chroot and it works:

    apt-get install python3 python3-dev python3-pip3 python3-setuptools python3-wheel

Btw it's pysha3 from requirements.txt which will surprisingly not build without python3-wheel.

**Comment by juestr** [comment]
OK I'll try that, in a few days.

**Comment by juestr** [comment]
I just opened #53.

**Comment by petertodd** [comment]
Merged, thanks!
