### ISSUE TITLE
'bitcoin' has no attribute 'SelectParams'

### ISSUE THREAD

**Issue by michaelplews** [opentimestamps/opentimestamps-client#55]
Completing the example with README.md

```
$ ~ > ./ots verify README.md.ots     
Assuming target filename is 'README.md'
Got 2 attestation(s) from cache
Traceback (most recent call last):
  File "./ots", line 34, in <module>
    args.cmd_func(args)
  File "/home/mike/Software/opentimestamps-client/otsclient/cmds.py", line 410, in verify_command
    if not verify_timestamp(detached_timestamp.timestamp, args):
  File "/home/mike/Software/opentimestamps-client/otsclient/cmds.py", line 338, in verify_timestamp
    proxy = args.setup_bitcoin()
  File "/home/mike/Software/opentimestamps-client/otsclient/args.py", line 99, in setup_bitcoin
    bitcoin.SelectParams('mainnet')
AttributeError: module 'bitcoin' has no attribute 'SelectParams'
```

I have installed all the dependencies. Am I missing something?

**Comment by petertodd** [comment]
Weird!

Can you tell us what python version your using, and what OS/distribution?

**Comment by petertodd** [comment]
Oh! I bet you installed the "bitcoin" python library from Vitalik, rather than the "python-bitcoinlib" python library...

**Comment by michaelplews** [comment]
I just checked again and I don't have bitcoin installed (although I did do this initially, but uninstalled after once I realised they weren't the same). I just checked again with `pip3 install -r requirements.txt` and I have all requirements satisfied.

Distro: Ubuntu 16.04.2 LTS
Python 3.5.2

**Comment by petertodd** [comment]
As in, you *now* have all requirements satisfied? Did that fix the problem?

I'm not sure if you can install both "bitcoin" and "python-bitcoinlib" at the same time; never tried it myself.

**Comment by petertodd** [comment]
Or I should say, I'm not sure what happens if you do that. :)

**Comment by michaelplews** [comment]
Yes, I now have all the requirements satisfied and that didn't fix the problem. Unless the `bitcoin` package is still hanging around somehow

I figured it out, turns out I had to manually `rm` the `bitcoin` directory from `python3.5/dist-packages` and reinstall `python-bitcoinlib`

Thanks for the help!

**Comment by petertodd** [comment]
Great! Glad to hear you got everything working.

If you could, it'd be a good idea to submit a pull-req noting this issue in the README!

**Comment by michaelplews** [comment]
I've submitted a pull request for this issue.

One more really quick question: how often do transactions occur with the bob and alice calendars? If there's a better place to ask this please let me know.
