### ISSUE TITLE
Setup.py does not create entry points

### ISSUE THREAD

**Issue by tweilbach** [opentimestamps/opentimestamps-client#61]
After grabbing the latest code and verifying all the dependencies I noticed that `pip` did not create/reference the entry points `ots` and `ots-git-gpg-wrapper` as it state on the tin:

```
 # To provide executable scripts, use entry points in preference to the
 # "scripts" keyword. Entry points provide cross-platform support and allow
 # pip to create the appropriate form of executable for the target platform.
    entry_points={
        'console_scripts': [
            'ots = otsclient.ots:main',
            'ots-git-gpg-wrapper = otsclient.git_gpg_wrapper:main',
        ],
```
Ran setup on Ubuntu 16.04 LTS. Also tried running setup with sudo, because permissions, but same result. Just to be clear - setup runs fine, the entry points just aren't created. Should `pip` be creating them or is the above code just a reference to the entry points that should be there (but are missing)?

Easily worked around by copying `ots` entry point from the previous version.

**Comment by tweilbach** [comment]
I'm closing this - I was looking in the wrong place. `ots` entry point was correctly created in `/usr/local/bin` just needed to restart terminal before I could reference it.

**Comment by petertodd** [comment]
Great! Glad to here it's working out for you now.
