### ISSUE TITLE
Stamp command should prompt if file exists

### ISSUE THREAD

**Issue by omarshibli** [opentimestamps/opentimestamps-client#63]
I think it would be nice if stamp command prompt the user if file exists.

Encountered behavior:
```bash
1. First run
➜  opentimstamps git:(master) ✗ ots stamp wee
Submitting to remote calendar https://a.pool.opentimestamps.org
Submitting to remote calendar https://b.pool.opentimestamps.org
Submitting to remote calendar https://a.pool.eternitywall.com

2. Second run
➜  opentimstamps git:(master) ✗ ots stamp wee
Submitting to remote calendar https://a.pool.opentimestamps.org
Submitting to remote calendar https://b.pool.opentimestamps.org
Submitting to remote calendar https://a.pool.eternitywall.com
Failed to create timestamp 'wee.ots': [Errno 17] File exists: 'wee.ots'
```

Suggested behavior:
1. Maybe show an error before submitting at all.
2. Or, prompt the user, file already exists and this operation will overwrite.

**Comment by petertodd** [comment]
By "prompt", do you mean give the user the chance to say "overwrite it anyway"?

**Comment by omarshibli** [comment]
yeah, overwrite or abort

**Comment by omarshibli** [comment]
just some context here, I was using this command with one file, in this case I think the behavior should be, if file exists the user should be prompted to overwrite, but it's getting complicated if multiple files getting passed, in this case what do you think the proper handling should be:
1. If no file exists, no prompt.
2. if some file exists, prompt with three options: abort, skip existing, overwrite
3. if all files exists, prompt with two options: abort, overwrite all

what do you think?

**Comment by petertodd** [comment]
Actually there's a *fourth* option: merge both timestamps. And that option itself has a potential failure mode: the file having changed since it was last timestamped.

Maybe the real question here, is under what circumstances would a user likely run `ots stamp` again? This stuff gets complex quickly, so I'd want to identity a common use-case to want to do anything but halt.

**Comment by omarshibli** [comment]
this issue open was filed while testing the tool, I will reopen if I can find a real use case to my suggestion.
