### ISSUE TITLE
Software code signing guidelines and considerations 

### ISSUE THREAD

**Issue by omarshibli** [opentimestamps/opentimestamps-client#69]
Hey, I'm working on FOSS project, we are in process of integrating public CI service and public package repositories, would be happy to use opentimestamps for code signing, we evaluated traditional code signing certificates, but perfer to stick with decentralized solutions as much as possible for now. would appreciate if we can get any feedback and thoughts about using opentimestamps for software code signing rather than traditional methods.

Any thoughts and feedback on this would be appreciated.

**Comment by petertodd** [comment]
Awesome!

Note that OTS timestamps on git commits are used in addition to PGP; they don't fully replace traditional PGP-signed commits.

Or do you have a use-case for something other than git commits?

Also, in general I always like to ask the question, what are you trying to *prevent* with your system?

**Comment by omarshibli** [comment]
We would like to get to a process where our software where applicable will be published with PGP + public attestation using OTS. as an another layer of validation.

**Comment by petertodd** [comment]
By "our software", do you mean software released as source or binaries?

**Comment by omarshibli** [comment]
both, could be source or binaries

**Comment by petertodd** [comment]
So what I'd recommend for source code, is to use git w/ the OTS git integration. Just sign with PGP, and timestamp with OTS.

For binaries, however you're distributing them, I'd sign the file w/ PGP, and then timestamp the PGP signature. *Don't* timestamp just the file itself - the big advantage of a timestamp is you can continue to verify the PGP signature securely even after the key that made it is no longer valid.

Beyond that, there's a *lot* more you can do. But the above is a good first start.

**Comment by omarshibli** [comment]
Thank you so much, that's a good start indeed.

**Comment by petertodd** [comment]
Glad to help!
