### ISSUE TITLE
Failure to timestamp a git commit

### ISSUE THREAD

**Issue by petertodd** [opentimestamps/opentimestamps-client#73]
Reported by @laanwj on commit https://github.com/bitcoin/bitcoin/commit/a36834f10b80cd349ed35e4d2a04c50a8e02f269

Possibly because the commit message was so long?

**Comment by laanwj** [comment]
I tried it three times, so it was reproducible back then at least, and fairly sure it's specific to the commit.

FWIW I haven't had the problem with any other commits before that, or since.

**Comment by petertodd** [comment]
@laanwj Fixed in master.

I'll do a release soon with this fix, and I also have a better way of handling the git wrapper thing that I want to implement for it as well.
