### ISSUE TITLE
ots-git-gpg-wrapper: error: unrecognized arguments: --rehash-trees

### ISSUE THREAD

**Issue by kanzure** [opentimestamps/opentimestamps-client#77]
Looks like `ots-git-gpg-wrapper` has lost a feature?

```
ots-git-gpg-wrapper: error: unrecognized arguments: --rehash-trees
```

**Comment by petertodd** [comment]
Not quite: it's now default behavior.

Planning to redesigning `ots-git-gpg-wrapper` entirely before the next release, which will remove all command line arguments.

**Comment by kanzure** [comment]
yeah ok, usability options/flags are a usability flaw anyway
