### ISSUE TITLE
Failed to create timestamp: need at least 2 attestations but received 0 within timeout

### ISSUE THREAD

**Issue by InnovativeInventor** [opentimestamps/opentimestamps-client#78]
Not sure what's happening when I try to timestamp the Qubes OS canaries. Here is my output:

```
Submitting to remote calendar https://a.pool.opentimestamps.org
Submitting to remote calendar https://b.pool.opentimestamps.org
Submitting to remote calendar https://a.pool.eternitywall.com
Failed to create timestamp: need at least 2 attestations but received 0 within timeout
```

Are the servers down or something?

**Comment by petertodd** [comment]
Are you sure networking is working in that VM? That error message means that none of the calendar servers could be contacted; the URL's above should all be accessible.

**Comment by InnovativeInventor** [comment]
I tried this on a remote linux server, and it works. But, when I try it on my mac doesn't work. `a.pool.opentimestamps.org` works when I ping it on both machines. Something interesting that I found out (might be related) is this:
```
$ verify ****.ots
Assuming target filename is '****'
Calendar https://alice.btc.calendar.opentimestamps.org: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)
Calendar https://bob.btc.calendar.opentimestamps.org: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)
Calendar https://finney.calendar.eternitywall.com: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)
```
Quite strange. `https://alice.btc.calendar.opentimestamps.org` uses Let's Encrypt, which should be trusted.

**Comment by petertodd** [comment]
Oh interesting! I have no idea what it'd be doing there, though I vaguely recall @RCasatta running into something similar before.

**Comment by RCasatta** [comment]
yeah, IIRC python3.6 on mac from sierra ships without default certs, please have a look at this resource http://www.cdotson.com/2017/01/sslerror-with-python-3-6-x-on-macos-sierra/ or search similar

**Comment by InnovativeInventor** [comment]
Thanks! I ended up having to install certify, which seems not 100% trustworthy because 
- It is a third party package
- Their website is down and has been for a while now
- I don't know if they decide to change the list of trusted certificates and their reasoning for doing so

Just as a note, the two options to add certs to python involve either doing: 
```
cd /Applications/Python\ 3.6/
./Install\ Certificates.command
```
or
```
pip3 install certifi 
```
But they both end up installing certifi, so anyone with macos is stuck with installing certifi for now to fix this issue.

**Comment by petertodd** [comment]
Thanks! We should probably add this to the README or something.
