### ISSUE TITLE
Reading from stdin is broken due to argparse bug

### ISSUE THREAD

**Issue by petertodd** [opentimestamps/opentimestamps-client#86]
@haraldschilly opened https://github.com/opentimestamps/python-opentimestamps/issues/31 in the wrong repo, so opening an issue here to track it.

**Comment by laanwj** [comment]
FYI the upstream issue https://github.com/opentimestamps/opentimestamps-client/issues/86 was fixed (in python 3.9/3.10)

**Comment by petertodd** [comment]
Ah good! Thanks for letting me know.
