### ISSUE TITLE
gpg wrapper fails in git worktree

### ISSUE THREAD

**Issue by laanwj** [opentimestamps/opentimestamps-client#87]
When using the gpg wrapper in a git worktree (out-of-tree checkout), the following error happens when signing:
```
Traceback (most recent call last):
  File "/.../.local/bin/ots-git-gpg-wrapper", line 11, in <module>
    sys.exit(main())
  File "/.../.local/lib/python3.5/site-packages/otsclient/git_gpg_wrapper.py", line 115, in main
    repo = git.Repo()
  File "/.../.local/lib/python3.5/site-packages/git/repo/base.py", line 161, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /.../projects/bitcoin/bitcoin/.git/worktrees/bitcoin-0.16
```
I think this is a problem with the upstream `git` python module.

**Comment by laanwj** [comment]
The issue seems to be due to buggy handling of the `GITDIR` environment variable in gitpython.

The funny thing is that `git.Repo()` works fine in a worktree **outside of the tool**. It correctly detects that the repository in the current directory is a worktree and sets the path accordingly
```python
/.../bitcoin/bitcoin-0.16$ python3
>>> import git
>>> git.Repo()
<git.Repo "/.../bitcoin/.git/worktrees/bitcoin-0.16">
>>> git.Repo('/.../bitcoin/bitcoin-0.16')
<git.Repo "/.../bitcoin/.git/worktrees/bitcoin-0.16">
>>> git.Repo('/.../bitcoin/.git/worktrees/bitcoin-0.16')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../.local/lib/python3.5/site-packages/git/repo/base.py", line 169, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /.../bitcoin/.git/worktrees/bitcoin-0.16
```

However, it looks like that when calling the gpg program, git itself (I think) has set `GIT_DIR` not to the current directory, but to the worktree link (`/.../bitcoin/.git/worktrees/bitcoin-0.16` in this case).
`git.Repo()` picks this up as argument, and somehow fails to grasp what kind of directory it is.

**Comment by laanwj** [comment]
I wonder, too. Haven't looked yet into how much work it would be to add worktree support, or whether there are alternatives to GitPython that do.

Or whether it's possible to temporarily work around this at the `opentimestamps-client` side - it doesn't sound to difficult to find the original git directory then use that  - would just have to be careful with 'current branch'.

I use worktrees for building and merging into version branches. So for the last few merges on 0.16 I had to disable the wrapper. Which is pretty lousy. For signing the `v0.16.1` tag I'm going to do a full clone.

**Comment by petertodd** [comment]
Heh, looks like Rust's git2 crate has worktree support, so maybe I can just rewrite it all in rust. :)

The git commit signing code shouldn't care about what branch it is, so all we really have to do is have a hack to figure out where the git directory is. Specifically, that hack would need to be added to https://github.com/opentimestamps/opentimestamps-client/blob/c2819c0f1fdb40c71924fd9cfbcdf4d655ce037c/otsclient/git_gpg_wrapper.py#L109

`git.Repo()` takes an optional directory argument, so it might be enough to just attempt to find the `.git` ourselves; in the case of a worktree, `.git` is a file:

    gitdir: /tmp/opentimestamps-client/.git/worktrees/ots-0.3.2

and in that directory there's another file, `gitdir`, which contains the actual path for `.git`:

```
$ cat gitdir 
/tmp/ots-0.3.2/.git
```

**Comment by laanwj** [comment]
Apparently this was fixed upstream for a while,
https://github.com/gitpython-developers/GitPython/pull/894
then reverted later due to performance regression
https://github.com/gitpython-developers/GitPython/issues/719

**Comment by real-or-random** [comment]
The simplest way to get the real directory seems to be `git rev-parse --git-path config`  (and then strip the trailing `config`).

**Comment by petertodd** [comment]
I believe this is fixed by the latest release: https://github.com/opentimestamps/opentimestamps-client/releases/tag/opentimestamps-client-v0.7.2

Thanks goes to @achow101 for the fix.
