### ISSUE TITLE
What does the timestamp stamp?

### ISSUE THREAD

**Issue by Soham3-1415** [opentimestamps/opentimestamps-client#94]
What part of the commit does the timestamp stamp when the git wrapper is used? Does the timestamp ignore the signature or does it stamp the signature as well as the rest of the commit?

If the timestamp does not stamp the signature, then it may be possible for an attacker to timestamp a malicious git commit and sign it later when a victim's key is compromised. Then using the timestamp to verify that the commit was signed before the key was compromised is useless.

**Comment by petertodd** [comment]
Good question!

The git commit and the signature itself are both timestamped, proving that the signature was in fact created in the past: https://github.com/opentimestamps/opentimestamps-client/blob/master/otsclient/git.py#L27

If you want to fully verify this for yourself, I'd suggest you go through the git-gpg-wrapper code, starting at: https://github.com/opentimestamps/opentimestamps-client/blob/master/otsclient/git_gpg_wrapper.py#L30

A fun homework exercise is to answer the question "What else is timestamped, in addition to the git commit and signature?" :)

**Comment by petertodd** [comment]
And yes, if we didn't do that, the attack you described would definitely work.

**Comment by Soham3-1415** [comment]
In https://github.com/opentimestamps/python-opentimestamps/blob/master/opentimestamps/core/git.py
it says that the git tree reshashed as a merkle tree, so individual files can have their timestamps extracted. So does the timestamp stamp the signature, commit, and the merkle root?
