### ISSUE TITLE
Feature: Allow filenames in file, or nul-terminated a la xargs, or allow sha256sum file format to provide sums directly

### ISSUE THREAD

**Issue by midnightmagic** [opentimestamps/opentimestamps-client#95]
The argument list can only be so long on some platforms; and in any event, a limit on open filehandles currently limits the OTS client from e.g. stamping a large directory full of files. If the hashing work is already done in another file (for example, in a sha256sum format file) then feeding that file, or at least a list of files, into the command-line would be a great way to help mass-stamp.

Thanks for the awesome tool!

(P.S. git file extraction works for trees of very small files, but it isn't great for extremely large trees of extremely large files and anyway the overhead is significant for no appreciable gain.)

**Comment by petertodd** [comment]
@midnightmagic What specific problems are you having with the git support? I personally use it for repo's with tens of thousands of small files in them with no issues; remember that it caches the results.

**Comment by midnightmagic** [comment]
I'm not currently using git; git doesn't deal so well with extremely large datasets. For that and various.. sigh..  other silly reasons I don't want to convert my filetree to use git to archive large numbers of files. It's not a huge issue; I mean I could just build my own pseudo-merkle structure and stamp the root. But feeding large numbers of filenames to the client would just be a nice-to-have.

I'm also super lazy—so honestly if I really needed to fix this I'd be modifying the tool or just building my own. Just thought.. eh. Nice-to-have. :)

**Comment by petertodd** [comment]
Have you tried git-annex? You might find that it works better than pure git.
