### ISSUE TITLE
Strange calendar server 'https://ots.btc..catallaxy.com'

### ISSUE THREAD

**Issue by jonathancross** [opentimestamps/opentimestamps-client#99]
I'm seeing this (malformed?) calendar server url when verifying a stamp:
`verify PendingAttestation('https://ots.btc..catallaxy.com')`

ots recognizes it's malformed at least:
`Ignoring attestation from calendar https://ots.btc..catallaxy.com: Calendar not in whitelist`

MacOS 10.13.6
ots installed via pip3 and working fine for everything else.

**Comment by FrancisPouliot** [comment]
We did a server migration and we had an error when switching DNS records. Sorry about that, it's fixed.

**Comment by jonathancross** [comment]
Confirmed: `Submitting to remote calendar https://ots.btc.catallaxy.com` -- Thanks!
